---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10
    image: joepublic/molecule-debian:10
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: debian11
    image: joepublic/molecule-debian:11
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: debian12
    image: joepublic/molecule-debian:12
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: fedora37
    image: joepublic/molecule-fedora:37
    command: /usr/sbin/init
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: fedora38
    image: joepublic/molecule-fedora:38
    command: /usr/sbin/init
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: rockylinux8
    image: joepublic/molecule-rockylinux:8
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: rockylinux9
    image: joepublic/molecule-rockylinux:9
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: ubuntu20_04
    image: joepublic/molecule-ubuntu:20.04
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: ubuntu22_04
    image: joepublic/molecule-ubuntu:22.04
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: ubuntu23_04
    image: joepublic/molecule-ubuntu:23.04
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
scenario:
  create_sequence:
    - create
  check_sequence:
    - cleanup
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
