---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: get service facts
      ansible.builtin.service_facts:

    - name: check for service (Debian, Ubuntu)
      ansible.builtin.assert:
        that: ansible_facts.services['apache2.service']['state'] == "running"
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: check for service (CentOS, Rocky, Fedora)
      ansible.builtin.assert:
        that: ansible_facts.services['httpd.service']['state'] == "running"
      when: ansible_distribution == "CentOS" or ansible_distribution == "Rocky" or ansible_distribution == "Fedora"
