---
# tasks file for molecule_docker_systemd
- name: set fact for package to install (Debian, Ubuntu)
  ansible.builtin.set_fact:
    package: 'apache2'
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: set fact for package to install (CentOS, Rocky, Fedora)
  ansible.builtin.set_fact:
    package: 'httpd'
  when: ansible_distribution == "CentOS" or ansible_distribution == "Rocky" or ansible_distribution == "Fedora"

- name: install service for testing
  ansible.builtin.package:
    name:
      - '{{ package }}'
    state: present
  when: package is defined

- name: make sure service is started
  ansible.builtin.systemd:
    daemon_reload: true
    name: '{{ package }}'
    state: started
