name: build and push Debian 11

on:
  schedule:
    - cron: '0 20 * * 0'
  push:
    paths:
      - 'debian/11/Dockerfile'

jobs:
  build-and-push-debian-11:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          file: debian/11/Dockerfile
          push: true
          tags: |
            joepublic/molecule-debian:11
            joepublic/molecule-debian:latest
            ghcr.io/Joe-Public/molecule-debian:11
            ghcr.io/Joe-Public/molecule-debian:latest
