name: build and push

on:
  schedule:
    - cron: '0 20 * * 0'
  push:
    paths:
      - '**/Dockerfile'

env:
  CENTOS_LATEST: 8  
  DEBIAN_LATEST: 11
  FEDORA_LATEST: 35
  UBUNTU_LATEST: 22.10

jobs:
  build-and-push-changed:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/Dockerfile

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: build and push changed Dockerfile
        run: |
          for FILE in ${{ steps.changed-files.outputs.all_changed_files }}
          do
            TAG_NAME=`cut -d / -f 2 <<< $FILE`
            DISTRIBUTION=`cut -d / -f 1 <<< $FILE`
            if [[ ("$DISTRIBUTION" == "centos" && "$CENTOS_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "debian" && "$DEBIAN_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "fedora" && "$FEDORA_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "ubuntu" && "$UBUNTU_LATEST" == "$TAG_NAME") ]]; then
              TAGS="--tag joepublic/molecule-$DISTRIBUTION:$TAG_NAME --tag joepublic/molecule-$DISTRIBUTION:latest --tag ghcr.io/joe-public/molecule-$DISTRIBUTION:$TAG_NAME --tag ghcr.io/joe-public/molecule-$DISTRIBUTION:latest"
            else
              TAGS="--tag joepublic/molecule-$DISTRIBUTION:$TAG_NAME --tag ghcr.io/joe-public/molecule-$DISTRIBUTION:$TAG_NAME"
            fi
            docker build $TAGS $DISTRIBUTION/$TAG_NAME/
            docker push -a joepublic/molecule-$DISTRIBUTION
            docker push -a ghcr.io/joe-public/molecule-$DISTRIBUTION
          done
