name: build and push all images

on:
  workflow_dispatch:
  schedule:
    - cron: '55 23 1 * *'

env:
  DEBIAN_LATEST: 12
  FEDORA_LATEST: 41
  UBUNTU_LATEST: 24.04
  UBUNTU_LTS: 24.04
  ROCKY_LATEST: 9
  FILES: >
    rockylinux/8/Dockerfile
    rockylinux/9/Dockerfile
    debian/11/Dockerfile
    debian/12/Dockerfile
    fedora/38/Dockerfile
    fedora/39/Dockerfile
    fedora/40/Dockerfile
    fedora/41/Dockerfile
    ubuntu/20.04/Dockerfile
    ubuntu/22.04/Dockerfile
    ubuntu/24.04/Dockerfile

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: build and push defined Dockerfile
        run: |
          for FILE in $FILES
          do
            TAG_NAME=`cut -d / -f 2 <<< $FILE`
            DISTRIBUTION=`cut -d / -f 1 <<< $FILE`
            TAGS="--tag joepublic/molecule-$DISTRIBUTION:$TAG_NAME --tag ghcr.io/joe-public/molecule-$DISTRIBUTION:$TAG_NAME"
            if [[ ("$DISTRIBUTION" == "centos" && "$CENTOS_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "debian" && "$DEBIAN_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "fedora" && "$FEDORA_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "ubuntu" && "$UBUNTU_LATEST" == "$TAG_NAME") || ("$DISTRIBUTION" == "rockylinux" && "$ROCKY_LATEST" == "$TAG_NAME") ]]; then
              TAGS="$TAGS --tag joepublic/molecule-$DISTRIBUTION:latest --tag ghcr.io/joe-public/molecule-$DISTRIBUTION:latest"
            fi
            if [[ ("$DISTRIBUTION" == "ubuntu" && "$UBUNTU_LTS" == "$TAG_NAME") ]]; then
              TAGS="$TAGS --tag joepublic/molecule-$DISTRIBUTION:lts --tag ghcr.io/joe-public/molecule-$DISTRIBUTION:lts"
            fi
            docker build --no-cache $TAGS $DISTRIBUTION/$TAG_NAME/
            docker push -a joepublic/molecule-$DISTRIBUTION
            docker push -a ghcr.io/joe-public/molecule-$DISTRIBUTION
          done
